{% set name = "awscli-local" %}
{% set version = "0.22.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 07c532c372753bf5f15426451dc91d6eec9de8779748049329a9a882bdac8a0b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - awscli
    - localstack-client
    - python >=3.6

test:
  commands:
    - awslocal -h

about:
  home: https://github.com/localstack/awscli-local
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Thin wrapper around the "aws" command line interface for use with LocalStack
  doc_url: https://pypi.org/project/awscli-local/
  dev_url: https://github.com/localstack/awscli-local

extra:
  recipe-maintainers:
    - mwilson8
    - mxr-conda
