{% set name = "awscli-local" %}
{% set version = "0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 226271fa7ad5d8aed3410c2065e40c94a5f5b5eb882c548b011500874106f8bb

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - awscli
    - localstack-client
    - python

test:
  commands:
    - awslocal -h

about:
  home: https://github.com/localstack/awscli-local
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Thin wrapper around the "aws" command line interface for use with LocalStack
  doc_url: https://pypi.org/project/awscli-local/
  dev_url: https://github.com/localstack/awscli-local

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - oblute
    - benhuff
